version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  postgres:
    image: postgres:11.6
    hostname: postgres
    environment:
      POSTGRES_USER: postgres # Must be the same as DB_USER below
      POSTGRES_PASSWORD: postgres # Must be the same as DB_PASSWORD below
      POSTGRES_DB: retroboard # Must be the same as DB_NAME below
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  pgadmin:
    image: dpage/pgadmin4:4.15
    depends_on:
      - postgres
    ports:
      - '8080:80' # Change 8080 to whatever port you want to access pgAdmin from
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@retrospected.com # Can be anything
      PGADMIN_DEFAULT_PASSWORD: admin # Please change this!
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  backend:
    image: antoinejaussoin/retro-board-backend:latest
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_NAME: retroboard # Must be the same as POSTGRES_DB above
      DB_USER: postgres # Must be the same as POSTGRES_USER above
      DB_PASSWORD: postgres # Must be the same as POSTGRES_PASSWORD above
      DB_HOST: postgres # Must be the name of the Postgres service above
      DB_PORT: 5432 # Don't change this.
      BACKEND_PORT: 3201 # Don't change this (or change it in nginx.conf as well)
      SQL_LOG: 'false' # Whether to log SQL queries in the console
      REDIS_ENABLED: 'true' # Whether to enable Redis
      REDIS_PORT: 6379 # Should match the Redis port
      REDIS_HOST: redis # Must be the name of the Redis service above
      SENTRY_URL: '' # Optional, Sentry URL (https://1234567890abcdef12345@sentry.io/1234567)
      SESSION_SECRET: changeme
      TWITTER_KEY:
      TWITTER_SECRET:
      GOOGLE_KEY:
      GOOGLE_SECRET:
      GITHUB_KEY:
      GITHUB_SECRET:
      BASE_URL: http://localhost:3000 # This must be the URL of the frontend app once deployed
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  frontend:
    image: antoinejaussoin/retro-board-frontend:latest
    depends_on:
      - backend
    ports:
      - '80:80' # Change the first 80 to whatever port you want to access Retrospected from
    environment:
      BACKEND_HOST: backend # This should be the name of the backend service
      BACKEND_PORT: 3201 # This should be the same as BACKEND_PORT on backend
      GA_ID: '' # Optional, Google Analytics ID (UA-1234456-7)
      SENTRY_URL: '' # Optional, Sentry URL (https://1234567890abcdef12345@sentry.io/1234567)
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

volumes:
  database:
  pgadmin:
