apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: rb-frontend
  template:
    metadata:
      labels:
        component: rb-frontend
    spec:
      containers:
        - name: rb-frontend
          image: antoinejaussoin/retro-board-frontend:2.1.4
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: rb-backend-cluster-ip-service
            - name: BACKEND_PORT
              value: '3201'
            - name: GA_ID
              value: ''
            - name: SENTRY_URL
              value: ''
            - name: GIPHY_API_KEY
              value: ''
