version: '3'
services:
  cypress:
    image: "cypress/included:4.4.0"
    ipc: host
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend
      - CYPRESS_backend_delay=30000
    working_dir: /e2e
    volumes:
      - ./:/e2e

  postgres:
    image: postgres:11.6
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: some-password
      POSTGRES_USER: postgres
      POSTGRES_DB: retroboard
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  backend:
    image: retrospected/backend:canary
    depends_on:
      - redis
    environment:
      SELF_HOSTED_ADMIN: 'your@email.com'
      DB_PASSWORD: some-password
      SESSION_SECRET: im-a-secret

    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  frontend:
    image: retrospected/frontend:canary
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  redis:
    image: redis:latest
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'


volumes:
  database:
  pgadmin: